[WIP]: Implement contest and search screen
mdgspace/codephile-mobile pull request #90
Opened 2022-02-16 01:30 UTC by aman-singh7

2022-02-23 17:08 UTC, praeclarumjj3 requested changes

2022-02-23 17:15 UTC, aman-singh7 commented on lib/presentation/search/search_screen.dart
> +                child: state.showSearches
Because you might have not logged in before or the token will be expired. Please login again.

2022-02-23 17:17 UTC, aman-singh7 commented on lib/presentation/contests/contests_screen.dart
> +                    // if (index >= (state.contest!.upcoming?.length ?? 0)) {
sorry I forget to remove these codes. :sweat_smile:

2022-02-23 17:18 UTC, praeclarumjj3 commented on lib/presentation/search/search_screen.dart
> +                child: state.showSearches
Do you have a test account?

2022-02-23 17:20 UTC, aman-singh7 commented on lib/presentation/search/search_screen.dart
> +                child: state.showSearches
sent on the channel.

2022-03-05 11:17 UTC, praeclarumjj3 approved these changes

2022-03-05 11:17 UTC, merged